### ISSUE TITLE
Error when loop a file each line

### ISSUE THREAD

**Issue by sancastlem** [dpetzold/aws-log-parser#9]
Hi,
I think there is an error in the module. If you have a log file with more than one line, and loop it in a for, appear this error:

```
[ERROR] UnknownHttpType: h
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 65, in lambda_handler
    print(next(generator_line))
  File "/opt/python/lib/python3.8/site-packages/aws_log_parser/parser.py", line 87, in log_parser
    yield log_type.model(*[
  File "/opt/python/lib/python3.8/site-packages/aws_log_parser/parser.py", line 88, in <listcomp>
    to_python(value, field) for value, field in zip(row, fields)
  File "/opt/python/lib/python3.8/site-packages/aws_log_parser/parser.py", line 73, in to_python
    return to_http_type(value)
  File "/opt/python/lib/python3.8/site-packages/aws_log_parser/parser.py", line 25, in to_http_type
    raise UnknownHttpType(value)END RequestId: 2506ce6c-92b8-483a-9748-ad9df3db45ad
```

My code:
```
# Build session S3
s3 = boto3.client('s3')
    	
# Obtaining the event notification for S3
for record in event['Records']:
            
    # Save the bucket name and key from the event
    bucket = record['s3']['bucket']['name']
    keyfile = record['s3']['object']['key']

    # Get the new log, content and split in lines
    obj = s3.get_object(Bucket=bucket, Key=keyfile)
    content = obj['Body'].read().decode('utf-8')
    lines = content.splitlines()

    # Loop each line and parse it
    for line in lines:
        print(line)
        generator_line = log_parser(line, LogType.LoadBalancer)
        print(next(generator_line))
```
In my case, I have an ELB where save the logs file in a bucket S3. I can access in each log file and print each line correctly in the for.

If you change the line **generator_line = log_parser(line, LogType.LoadBalancer)** by **generator_line = log_parser(lines, LogType.LoadBalancer)**, then the error doesn't appear, but only parse the first line of the log file. I attach an [example log](https://github.com/dpetzold/aws-log-parser/files/5426116/example-log.log) file for test.

I'll be waiting for your answer.

Thanks and regards.

**Comment by dpetzold** [comment]
Hello @sancastlem. I think you just want this:

```
generator_line = log_parser(content, LogType.LoadBalancer)
```

The parser expects a generator. I'll look into improving the examples.

**Comment by sancastlem** [comment]
Hi @dpetzold,
thanks for the reply, but doesn't work. Appear the same error.

But, finally, I've get solved the problem. This it my code:

```
# Build session S3
s3 = boto3.client('s3')
    	
# Obtaining the event notification for S3
for record in event['Records']:
            
    # Save the bucket name and key from the event
    bucket = record['s3']['bucket']['name']
    keyfile = record['s3']['object']['key']

    # Get the new log and content, split in lines and parse each line
    obj = s3.get_object(Bucket=bucket, Key=keyfile)
    content = obj['Body'].read().decode('utf-8')
    lines = content.splitlines()
    generator_line = log_parser(lines, LogType.LoadBalancer)
            
    for line in generator_line:
        print(line)
```
With this, now I can loop every line of my log file.

Thanks and regards! :)
